site_name: Build Serverless applications using IaC
repo_url: https://github.com/fun-with-serverless/cloud-native-reboot
site_url: https://cloud-native-reboot.designfor.cloud
edit_uri: edit/master/docs/
repo_name: cloud-native-reboot

theme:
  name: material
  features:
    - content.code.copy
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.code.annotate
  icon:
    logo: material/test-tube
    favicon: images/test-tube.svg
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - social
  - search
extra: 
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/fun-with-serverless/cloud-native-reboot/issues/new/choose" target="_blank" rel="noopener">openning an issue</a>.
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/TServerless
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/efime/

nav:
  - Introduction: 'index.md'
  - Serverless:
    - What is Serverless: './serverless/what-is-serverless.md'
    - Known AWS Serverless Services: './serverless/serverless-services.md'
  - What is IaC: './what-is-iac.md'
  - AWS SAM: 
    - Hello SAM 👋: './aws-sam/hello-sam.md'
    - Implement 'Get Subscribers': './aws-sam/get-subscribers.md'
    - Implement 'Add Subscribe': './aws-sam/add-subscribers.md'
    - Implement 'Schedule Message': './aws-sam/schedule-message.md'
    - Implement 'Send Message': './aws-sam/send-message.md'
    - 🏁 Grand finale 🏁: './aws-sam/add-authorizer.md'
    - Cleanup: './aws-sam/deletion.md'
  - CDK:
    - Hello CDK 👋: './cdk/hello-cdk.md'
    - Implement 'Get Subscribers': './cdk/lambda-api-gateway.md'
    - Adding a Lambda Layer: './cdk/adding-layer.md'
    - Using Constructs: './cdk/iac-encapsulation.md'
    - 🏁 Grand finale 🏁: './cdk/finish-them.md'
    - Cleanup: './cdk/deletion.md'